import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "./Components";
import { MobileProvider } from "./Elements/hooks";
import React from "react";
import { headers } from "next/headers";
import { VideoStatusProvider } from "./Elements/hooks/globalHooks/VideoStatusContext ";

export const metadata: Metadata = {
  title: "Total Privacy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const userAgent = (await headersList).get("user-agent") || "";
  const isMobile =
    /Android|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i.test(userAgent);

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="./IconTotalPrivacy.png" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./IconTotalPrivacy.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="./IconTotalPrivacy.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="./IconTotalPrivacy.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={""}>
        <MobileProvider initialMobileState={isMobile}>
          <VideoStatusProvider>
            <NavBar />
            {children}
          </VideoStatusProvider>
        </MobileProvider>
      </body>
    </html>
  );
}
